### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by mojtabamarashee** [Bogdan-Lyashenko/react-redux-game-starter#1]
Hi
how to use it?

**Comment by Bogdan-Lyashenko** [comment]
Hi) 
Well, actually you need to clone the repository locally, then - npm install, npm start.

So, it’s base for your project, then just extend it with more features.

**Comment by mojtabamarashee** [comment]
Thanks for reply

Do you (or anyone else)  have extended it for a more complex game?
Do you have any idea for a specific game?

**Comment by Bogdan-Lyashenko** [comment]
No, I didn’t extend. Well, in fact any board-games can have this as a base. Any game when you have multiple players, play “step” in a queue and evaluate game phase based on steps where made. Yeah, it’s more or less all board games.

**Comment by mojtabamarashee** [comment]
Any TODO idea?
(I love react and looking for a start point for a project)

**Comment by Bogdan-Lyashenko** [comment]
Well, maybe “tic tac toe”, should be pretty simple.

**Comment by mojtabamarashee** [comment]
Thanks
